[DEFAULT]
naming_format = {journal}_{year}_{first_author}_{title}

[ABBREVIATIONS]
Journal of Geophysical Research: Solid Earth = JGRSE
Earth and Planetary Science Letters = EPSL
Journal of Geophysical Research = JGR
Earth-Science Reviews = ESR
Journal of Structural Geology = JSG
Nature = Nat
Science = Sci
Geophysical Research Letters = GRL
Earthquake Science = EqS
# 用户可以添加更多缩写，例如：
# Proceedings of the National Academy of Sciences = PNAS